server.port=${PORT:8080}
logging.level.org.atmosphere=warn
vaadin.launch-browser=true
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example

spring.datasource.url=jdbc:oracle:thin:@192.168.10.2:1521:orcl?oracle.jdbc.defaultNChar=true
spring.datasource.username=stajdemo
spring.datasource.password=stajdemo
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.connection-init-sql=ALTER SESSION SET NLS_LANGUAGE='TURKISH' NLS_TERRITORY='TURKEY'